version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "7:00"
    groups:
      all-actions:
        patterns: [ "*" ]
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
