name: 🧽 Format checks

on:
  push:
    branches:
      - master
      - release-**
  pull_request:
    branches:
      - master
      - release-**
  issue_comment:
    types: [created]

jobs:
  pre-commit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/github-script@v5
        if: ${{ github.event.issue.pull_request }}
        id: get-pr
        with:
          script: |
            const prUrl =  context.payload.issue.pull_request.url;
            const octokit = github.getOctokit(token);

            const prDetails = await octokit.request(`GET ${prUrl}`);
            const headRef = prDetails.data.head.ref;
            const headSha = prDetails.data.head.sha;
            const headRepo = prDetails.data.head.repo.full_name;

            core.setOutput('head_ref', headRef);
            core.setOutput('head_sha', headSha);
            core.setOutput('head_repo', headRepo);

      - uses: actions/checkout@v2
        if: ${{ github.event.issue_comment.pull_request }}
        with:
          repository: ${{ steps.get-pr.outputs.head_repo }}
          ref: ${{ steps.get-pr.outputs.head_sha }} # sha

      - uses: actions/checkout@v2
        if: ${{ !github.event.issue.pull_request }}

      - uses: khan/pull-request-comment-trigger@master
        id: run-fixes
        if: ${{ github.event.issue.pull_request }}
        with:
          trigger: '@qfield-fairy style please'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.FAIRY_TOKEN }}'

      - name: Install Requirements
        run: |
            sudo apt install -y \
              shellcheck

      - name: Check pre-commit hooks
        uses: pre-commit/action@v2.0.3

      - name: Comment
        uses: thollander/actions-comment-pull-request@main
        if: failure() && steps.run-fixes.outputs.triggered != 'true' && github.event.issue.pull_request
        with:
          message: |
            Code formatting issues have been detected.
            Reply with `@qfield-fairy style please` to fix it up 🪄.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: EndBug/add-and-commit@v8.0.1
        if: failure() && steps.run-fixes.outputs.triggered == 'true' && github.event.issue.pull_request
        with:
          author_name: Style Fairy
          author_email: fairy@qfield.org
          message: 'Committing style changes'
          branch: ${{ steps.get-pr.outputs.head_ref }} # branch name
        env:
          GITHUB_TOKEN: ${{ secrets.FAIRY_TOKEN }}
